/** @type {import('tailwindcss').Config} */
// إعداد Tailwind المبني مسبقاً (بديل Tailwind Play CDN غير المخصّص للإنتاج).
// يمسح كل القوالب EJS، ويضمّ باليتة Material Design 3 المستخدمة في الواجهة.
module.exports = {
  content: ['./views/**/*.ejs'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#264778',
        'on-error-container': '#93000a',
        'on-secondary-container': '#55656d',
        outline: '#747780',
        'on-primary-container': '#7594ca',
        'on-secondary-fixed': '#0d1e25',
        primary: '#001736',
        'surface-bright': '#f8f9fb',
        secondary: '#506169',
        'surface-variant': '#e0e3e5',
        'primary-container': '#002b5b',
        'on-primary-fixed': '#001b3d',
        'surface-container-high': '#e6e8ea',
        'on-error': '#ffffff',
        'surface-dim': '#d8dadc',
        background: '#f8f9fb',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#d6e3ff',
        'on-surface-variant': '#43474f',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        tertiary: '#201600',
        'inverse-primary': '#a9c7ff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffdf9e',
        'tertiary-fixed-dim': '#e2c382',
        'secondary-container': '#d1e2ec',
        'on-background': '#191c1e',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#394951',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-fixed': '#261a00',
        'secondary-fixed': '#d4e5ef',
        'secondary-fixed-dim': '#b8c9d3',
        'on-tertiary-fixed-variant': '#59440f',
        'error-container': '#ffdad6',
        'surface-tint': '#405f91',
        'tertiary-container': '#3a2900',
        'primary-fixed-dim': '#a9c7ff',
        'outline-variant': '#c4c6d0',
        'inverse-on-surface': '#eff1f3',
        'surface-container': '#eceef0',
        surface: '#f8f9fb',
        'on-tertiary-container': '#ac8f54',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  // نفس إضافات Play CDN التي كانت مستخدمة في apply.ejs/success.ejs
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
